name: Fetch EURIBOR
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v2
      - name: Install JQ
        run: sudo apt-get install jq
      - run: |
          curl 'https://www.euribor-rates.eu/umbraco/api/euriborpageapi/highchartsdata?series[0]=2' | \
          jq --raw-output '["timestamp","rate"], .[0].Data[] | [.[0], .[1]] | @csv' > 3months.csv
          curl 'https://www.euribor-rates.eu/umbraco/api/euriborpageapi/highchartsdata?series[0]=3' | \
          jq --raw-output '["timestamp","rate"], .[0].Data[] | [.[0], .[1]] | @csv' > 6months.csv
          curl 'https://www.euribor-rates.eu/umbraco/api/euriborpageapi/highchartsdata?series[0]=4' | \
          jq --raw-output '["timestamp","rate"], .[0].Data[] | [.[0], .[1]] | @csv' > 12months.csv
      - uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: Update EURIBOR
      
